language: python

install:
    - pip install flake8 fabric pytz Flask-Testing mechanize coveralls nose
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -qq
    - sudo apt-get install nodejs build-essential dpkg-dev

before_script:
    - sudo mkdir -m 777 /etc/lwp
    - sudo mkdir -p /var/lwp
    - sudo cp lwp.db /var/lwp
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/mock-lxc
    # mock the presence of lxc-templates
    - sudo mkdir -p /usr/share/lxc/templates
    - sudo touch /usr/share/lxc/templates/lxc-busybox /usr/share/lxc/templates/lxc-ubuntu

script:
    - flake8 --ignore=E501,E402 lwp/ bin/lwp
    - fab build_assets
    - ./setup.py develop
    # test the genearation of secret file without lwp.conf
    - nosetests --cover-package=lwp --with-coverage tests/utils.py
    - cp lwp.example.conf /etc/lwp/lwp.conf
    - nosetests --cover-package=lwp --with-coverage tests/{auth,api,browser,lxc_lite,mock_lxc}.py

after_success:
  coveralls
