language: python

install:
    - pip install flake8 fabric pytz Flask-Testing coveralls
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -qq
    - sudo apt-get install nodejs build-essential dpkg-dev

before_script:
    - sudo mkdir -m 777 /etc/lwp
    - cp lwp.example.conf /etc/lwp/lwp.conf
    - sudo mkdir -p /var/lwp
    - sudo cp lwp.db /var/lwp
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/mock-lxc

script:
    - flake8 --ignore=E501,E402 lwp/ bin/lwp
    - fab build_assets
    - ./setup.py develop
    - coverage run --source=lwp tests/webif.py
    - coverage run -a --source=lwp tests/mock_lxc.py
    - coverage run -a --source=lwp tests/utils.py

after_script:
  coveralls
